import React, { useState, forwardRef, useImperativeHandle } from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { format } from "date-fns";

function escapeHtml(s) {
  if (!s) return "";
  return String(s).replace(
    /[&<>"']/g,
    (c) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      })[c],
  );
}

async function ensureReadmes(repos) {
  for (const r of repos) {
    if (r.hasReadme === null) {
      try {
        const res = await fetch(
          `https://api.github.com/repos/${r.full_name}/readme`,
          {
            headers: { Accept: "application/vnd.github.v3.raw" },
          },
        );
        if (res.ok) {
          r.readme = await res.text();
          r.hasReadme = true;
        } else {
          r.readme = null;
          r.hasReadme = false;
        }
      } catch (e) {
        r.readme = null;
        r.hasReadme = false;
      }
    }
  }
  return repos;
}

function buildIndexHtml(userData, repos, theme) {
  const title = escapeHtml(userData.name || "Portfolio");
  const bio = escapeHtml(userData.bio || "");
  const linksHtml = (userData.links || [])
    .map((l) => `<a href="${escapeHtml(l.url)}">${escapeHtml(l.label)}</a>`)
    .join(" | ");

  const projectsHtml = repos
    .map((r) => {
      const desc =
        r.hasReadme && r.readme
          ? r.readme.split("\n\n")[0]
          : r.description || "No description available";
      return ` <article class="project"><h3><a href="${escapeHtml(r.html_url)}">${escapeHtml(r.name)}</a></h3><p>${escapeHtml(desc)}</p><p class="meta">${escapeHtml(r.language || "")} • ⭐ ${r.stargazers_count || 0} • ${escapeHtml(format(new Date(r.updated_at), "PPP"))}</p></article>`;
    })
    .join("\n");

  const css = `:root{--bg:#f7fafc;--card-bg:#ffffff;--text:#0f1724;--muted:rgba(15,23,36,0.68);--accent:#ff6b6b;--border:#e6eef4}body{font-family:system-ui,Segoe UI,Roboto,-apple-system,Arial;margin:0;padding:24px;background:var(--bg);color:var(--text)}header{border-bottom:1px solid var(--border);padding-bottom:12px;margin-bottom:18px}h1{margin:0}a{color:var(--accent)} .project{border:1px solid var(--border);padding:12px;border-radius:6px;margin-bottom:12px;background:var(--card-bg)}footer{color:rgba(15,23,36,0.68)}`;

  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${css}</style></head><body><header><h1>${title}</h1><p>${bio}</p><p>${linksHtml}</p></header><main>${projectsHtml}</main><footer style="margin-top:24px;border-top:1px solid var(--border);padding-top:12px;">Generated by Profilely — deploy to Vercel by uploading contents.</footer></body></html>`;

  return { html, css };
}

const Exporter = forwardRef(function Exporter({ repos, userData, theme }, ref) {
  const [busy, setBusy] = useState(false);

  async function performExport() {
    setBusy(true);
    try {
      const toInclude = (repos || []).slice();
      await ensureReadmes(toInclude);
      const { html } = buildIndexHtml(userData || {}, toInclude, theme);

      const zip = new JSZip();
      zip.file("index.html", html);
      zip.file(
        "README.md",
        `# Exported portfolio\n\nThis static site was generated by Profilely.\n\n## Deploy on Vercel\n\n1. Unzip the archive.\n2. Create a new Git repository and push to GitHub (or use the Vercel dashboard to upload).\n3. On Vercel, import the repository and deploy (no build step required for static HTML).\n\nAlternatively, use the Vercel CLI from the folder: vercel\n`,
      );
      const blob = await zip.generateAsync({ type: "blob" });
      saveAs(blob, "profilely-portfolio.zip");
    } catch (e) {
      console.error(e);
      alert("Export failed: " + (e && e.message));
    } finally {
      setBusy(false);
    }
  }

  useImperativeHandle(ref, () => ({
    exportZip: performExport,
  }));

  return (
    <div className="card exporter">
      <h2>Export</h2>
      <p className="muted">Download static site</p>
      <div className="row">
        <button
          onClick={performExport}
          disabled={busy || (repos || []).length === 0}
        >
          {busy ? "Preparing…" : "Download static site (.zip)"}
        </button>
      </div>
    </div>
  );
});

export default Exporter;
